artifact_location: /home/stockpred-notebook/work/Chapter03/192.168.178.106:8000/0
creation_time: 1704994752359
experiment_id: '0'
last_update_time: 1704994752359
lifecycle_stage: active
name: Default
