version: '3.9'

services:
  postgres:
    container_name: postgres
    build:
      context: ./docker/postgres
    image: postgres:12.7-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./${POSTGRES_STORE}:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, -U postgres, pg_isready]
      interval: 2s
      timeout: 5s
      retries: 10

